version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./production.Dockerfile
    env_file:
      - backend/.env
    volumes:
      - ./backend/:/app
    ports:
      - 8000:8000
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ./production.Dockerfile
    volumes:
      - ./frontend/:/app
    depends_on:
      - backend
    ports:
      - 80:80
    restart: always
