import core.models.customer
import core.models.fabric
import core.models.curtain_system
import core.models.sewing_method
import core.models.foam
import core.models.quote
import core.models.quote_entry
import core.models.curtain_quote_entry
import core.models.upholster_quote_entry
import core.models.sale
