# Generated by Django 2.2 on 2023-06-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_full_name', models.CharField(max_length=80)),
                ('_cell_number', models.IntegerField()),
                ('_address', models.CharField(max_length=80)),
                ('_email', models.CharField(max_length=80)),
            ],
        ),
    ]
