# Generated by Django 2.2 on 2023-07-10 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurtainSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nombre')),
                ('_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Sistema de cortina',
                'verbose_name_plural': 'Sistemas de cortinas',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_full_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nombre completo')),
                ('_cell_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_code', models.CharField(blank=True, db_index=True, max_length=4, null=True, unique=True, verbose_name='Código')),
                ('_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre')),
                ('_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de la tela')),
            ],
            options={
                'verbose_name': 'Tela',
                'verbose_name_plural': 'Telas',
            },
        ),
        migrations.CreateModel(
            name='Foam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(blank=True, max_length=70, null=True, verbose_name='Tipo')),
                ('_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Espuma',
                'verbose_name_plural': 'Espumas',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número')),
                ('_seller', models.CharField(blank=True, max_length=80, null=True, verbose_name='Vendedor')),
                ('_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Descuento')),
                ('_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('_total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo total')),
                ('_observations', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='core.Customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='QuoteEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_product_quantity', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('_room', models.CharField(blank=True, choices=[('LIVING', 'Living'), ('COMEDOR', 'Comedor'), ('CUARTO', 'Cuarto'), ('COCINA', 'Cocina'), ('BAÑO', 'Baño'), ('LAVADERO', 'Lavadero'), ('VESTIDOR', 'Vestidor'), ('OTRO', 'Otro')], max_length=250, null=True, verbose_name='Ambiente')),
                ('_installation', models.BooleanField(default=False, verbose_name='Instalación')),
                ('_installation_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de instalación')),
                ('_subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('_total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo total')),
                ('_fabric_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancho de la tela')),
                ('_fabric_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Alto de la tela')),
                ('_fabric_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color de la tela')),
                ('_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_entry', to='core.Quote', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Entrada de cotización',
                'verbose_name_plural': 'Entradas de cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='SewingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nombre')),
                ('_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Método de confección',
                'verbose_name_plural': 'Métodos de confección',
            },
        ),
        migrations.CreateModel(
            name='UpholsterQuoteEntry',
            fields=[
                ('quoteentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.QuoteEntry')),
                ('_foam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upholster_quote_entry', to='core.Foam', verbose_name='Espuma')),
            ],
            options={
                'verbose_name': 'Entrada de cotización de tapicería',
                'verbose_name_plural': 'Entradas de cotizaciones de tapicerías',
            },
            bases=('core.quoteentry',),
        ),
        migrations.CreateModel(
            name='CurtainQuoteEntry',
            fields=[
                ('quoteentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.QuoteEntry')),
                ('_sewing_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curtain_quote_entry', to='core.SewingMethod', verbose_name='Confección')),
                ('_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curtain_quote_entry', to='core.CurtainSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Entrada de cotización de cortinería',
                'verbose_name_plural': 'Entradas de cotizaciones de cortinería',
            },
            bases=('core.quoteentry',),
        ),
    ]
