# Generated by Django 3.2.20 on 2023-07-16 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_core_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upholsterquoteentry',
            options={'verbose_name': 'Entrada de cotización de tapicería', 'verbose_name_plural': 'Entradas de cotizaciones de tapicería'},
        ),
        migrations.AddField(
            model_name='quoteentry',
            name='_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_entry', to='core.fabric', verbose_name='Tela'),
        ),
    ]
