# Generated by Django 3.2.20 on 2024-03-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_all_core_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='_approved',
            field=models.BooleanField(default=False, verbose_name='Aprobada'),
        ),
        migrations.AddField(
            model_name='sale',
            name='_fabric_requested',
            field=models.BooleanField(default=False, verbose_name='Telas encargadas'),
        ),
        migrations.AddField(
            model_name='sale',
            name='_order_shipped',
            field=models.BooleanField(default=False, verbose_name='Orden enviada'),
        ),
        migrations.AddField(
            model_name='sale',
            name='_systems_requested',
            field=models.BooleanField(default=False, verbose_name='Sistemas encargados'),
        ),
        migrations.AddField(
            model_name='sale',
            name='_tracking_state',
            field=models.CharField(blank=True, choices=[('CREADA', 'Creada'), ('EN_TALLER', 'En Taller'), ('LISTO_PARA_ENTREGAR', 'Listo para entregar'), ('FINALIZADA', 'Finalizada')], default='CREADA', max_length=250, null=True, verbose_name='Estado'),
        ),
    ]
