# Generated by Django 3.2.20 on 2024-04-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_state_and_controls_to_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecoEricaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_fabric_surcharge_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Porcentaje de sobreprecio de la tela')),
                ('_installation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de instalación')),
                ('_sewing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de confección')),
            ],
        ),
    ]
