# Generated by Django 3.2.20 on 2023-07-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer__email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtainsystem',
            name='_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de la tela'),
        ),
        migrations.AlterField(
            model_name='foam',
            name='_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo total'),
        ),
        migrations.AlterField(
            model_name='quoteentry',
            name='_installation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de instalación'),
        ),
        migrations.AlterField(
            model_name='quoteentry',
            name='_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo total'),
        ),
        migrations.AlterField(
            model_name='sewingmethod',
            name='_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
