# Generated by Django 3.2.20 on 2024-04-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_populate_decoerica_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decoericasettings',
            options={'verbose_name': 'Configuración general', 'verbose_name_plural': 'Configuraciones generales'},
        ),
        migrations.AddField(
            model_name='fabric',
            name='_category',
            field=models.CharField(blank=True, choices=[
                ('VOILES_GASAS_Y_LINOS_PARA_CORTINAS', 'VOILES, GASAS Y LINOS PARA CORTINAS'),
                ('BLACK_OUT_SUN_OUT', 'BLACK OUT / SUN OUT'),
                ('ARRUGADOS_OPACOS_Y_JAQ_LIVIANOS', 'ARRUGADOS, OPACOS Y JAQ. LIVIANOS'),
                ('PARA_MANTAS_Y_FUNDAS', 'PARA MANTAS Y FUNDAS'), ('BORDADOS', 'BORDADOS'),
                ('TERCIOPELOS_Y_LINOS', 'TERCIOPELOS Y LINOS'),
                ('LINOS_PARA_TAPICERIA_Y_FUNDAS', 'LINOS PARA TAPICERIA Y FUNDAS'),
                ('PANAS_LISAS_Y_TEXTURADAS', 'PANAS LISAS Y TEXTURADAS'),
                ('OUTDOOR_USO_EXTERIOR', 'OUTDOOR (USO EXTERIOR)'), ('SIMIL_CUERO', 'SIMIL CUERO'),
                ('JAQUARDS_DE_1_40_Y_2_80_DE_ANCHO', 'JAQUARDS DE 1,40 Y  2,80 DE ANCHO'), ('ESTAMPADOS', 'ESTAMPADOS'),
                ('CHENILES', 'CHENILES')], max_length=250, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='_description_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True,
                                      verbose_name='Descripción ancho'),
        ),
    ]
