# Generated by Django 3.2.20 on 2023-08-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230716_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtainquoteentry',
            name='_sewing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de confección'),
        ),
        migrations.AddField(
            model_name='curtainquoteentry',
            name='_system_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de sistema'),
        ),
        migrations.AddField(
            model_name='quoteentry',
            name='_fabric_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo por tela'),
        ),
    ]
