# Generated by Django 3.2.20 on 2023-10-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230731_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='upholsterquoteentry',
            name='_foam_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de espuma'),
        ),
        migrations.AddField(
            model_name='upholsterquoteentry',
            name='_sewing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de confección'),
        ),
        migrations.AddField(
            model_name='upholsterquoteentry',
            name='_sewing_method',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Confección'),
        ),
    ]
