# Generated by Django 3.2.20 on 2023-10-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20231008_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
