# Generated by Django 3.2.20 on 2023-10-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_quote__number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteentry',
            name='_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
    ]
